Show how long the queue will last
flo-bit/youtube-party-dj pull request #57
Opened 2024-06-27 19:59 UTC by tobidwest

#49

2024-06-29 15:35 UTC, flo-bit requested changes

2024-06-29 15:35 UTC, flo-bit commented on common/page.tsx
> +            {always(() =>
the text returned here needs a dark mode text color

2024-06-29 15:35 UTC, flo-bit commented on common/page.tsx
> +  function addDurations(duration1, duration2) {
this function gives me lots of warnings from my typescript thingy
- duration1 and duration2 are not typed
- all except the last `let` should be a `const`
- seconds probably shouldn't be type 'string' | 'number' (`String(n).padStart(1, '0')` may be interesting here)

Also I think it'd be good to move that to some other file, so we don't clutter up our main file, maybe a new `/common/helper.ts`, what do you think?

2024-06-29 15:35 UTC, flo-bit commented on common/page.tsx
> +  window.timeLeft = timeLeft;
why are we doing this?

2024-06-29 15:35 UTC, flo-bit commented on common/client.tsx
we really have to setup some common prettier settings ^^

is there any change except for formatting in this file? I can't find any

2024-06-29 18:28 UTC, tobidwest commented on common/client.tsx
no but it was indeed Prettier :)

2024-06-29 18:29 UTC, tobidwest commented on common/page.tsx
> +  window.timeLeft = timeLeft;
leftover from debugging, dropped that

2024-06-29 18:38 UTC, tobidwest commented
See #eaa383293f152866202a1cd7e7b12902a3e52ab6

2024-06-29 18:38 UTC, tobidwest commented
See eaa383293f152866202a1cd7e7b12902a3e52ab6

2024-07-02 00:58 UTC, flo-bit approved these changes
👍

2024-07-02 00:58 UTC, merged